export const LOCATORS = {
    searchInput: 'input[name=search]',
    searchButton: 'button[type=submit]',
    firstHeading: '#firstHeading',
    randomArticleLink: 'text=Random article',
    loginLink: 'text=Log in',
    createAccountLink: 'text=Create account',
    spanishLangLocator: 'text=Español',
    externalLinksLocator: 'a.external',
    notFoundResultLocator: '.mw-search-nonefound',
    mainPageDecsriptionLoactor: '#n-mainpage-description',
    contentSectionLocator: '#mw-content-text',
    referencesSectionLocator: '#References',
    externalLinksSectionLocator: '#External_links',
    sideBarContentLocator: '#vector-toc-pinned-container',
    mainMenuLocator: '#p-navigation',
    footerLocator: '#footer',
    loginLinkLocator: '#pt-login-2',
    testTypeLocator: 'a[href="#Testing_types"]',
    headerTestTypeTextLocator: 'h2:has-text("Testing types")',
};
